#!/usr/bin/env bash

set -e

# create new proxy token
TOKEN=`openssl rand -hex 32`
echo $TOKEN > .proxytoken

# replace secrets
sed -i '' -e "s/^  secretToken.*/  secretToken: \"$TOKEN\"/" secret-config.yaml
ID=`cat .clientid`
sed -i '' -e "s/^    clientId.*/    clientId: \"$ID\"/" secret-config.yaml
SECRET=`cat .clientsecret`
sed -i '' -e "s/^    clientSecret.*/    clientSecret: \"$SECRET\"/" secret-config.yaml

# update repo
helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
helm repo update

# install jupyterhub on the cluster
echo "Installing pangeo."
helm install jupyterhub/jupyterhub --version=v0.7-80d1391 --name=pangeo --namespace=pangeo --timeout=600 -f secret-config.yaml -f jupyter-config.yaml

# unreplace secrets
sed -i '' -e "s/^  secretToken.*/  secretToken: SECRET/" secret-config.yaml
sed -i '' -e "s/^    clientId.*/    clientId: ID/" secret-config.yaml
sed -i '' -e "s/^    clientSecret.*/    clientSecret: SECRET/" secret-config.yaml
