#!/usr/bin/env bash

# move into pangeo directory
PANGEO_DIR='/Users/tjc/research/flowmow/pangeo'
cd $PANGEO_DIR

# check git status
git diff --exit-code > /dev/null

if [ $? -eq 0 ]; then
  set -e

  # get commit hash for tag
  TAG=`git rev-parse --short HEAD`

  # update worker-template tag
  cd "$PANGEO_DIR/docker"
  sed -i '' "s/    image.*/    image: tjcrone\/pangeo-notebook:${TAG}/" worker-template.yaml

  # build notebook
  NAME='tjcrone/pangeo-notebook'
  docker build --no-cache -t "$NAME:$TAG" .

  # push notebook
  docker push "$NAME:$TAG"

  # update jupyter-config
  cd $PANGEO_DIR
  sed -i '' "s/    tag.*/    tag: ${TAG}/" jupyter-config.yaml

else
    printf "\nPlease stash or commit your changes before updating the Pangeo images.\n\n"
fi
